cudami:
  server:
    url: http://localhost:9000
    #url: https://api-dev.digitale-sammlungen.de/cudami

dfg:
  rights:
    owner: "Bayerische Staatsbibliothek"
    owner-contact: "mailto:mdz@digitale-sammlungen.de"
    owner-logo: "https://dfg-viewer.de/typo3temp/assets/images/d08200e38c0994139590ea9ad0b5c4fa.jpg"
    owner-site-url: "https://www.bsb-muenchen.de/"

iiif:
  identifier:
    namespaces:
      - 'mdz-obj'
      - 'mdz-obj-child'
  presentation:
    #baseUrl: "http://localhost:23232/presentation/v2/"
    baseUrl: "https://api-dev.digitale-sammlungen.de/iiif/presentation/v2/"

management:
  endpoints:
    web:
      base-path: "/monitoring"
      exposure:
        include: "*"
  server:
    port: 18080

server:
  port: 8080
  server-header: "@project.name@ v@project.version@"

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: MONITORING