cudami:
  server:
    url: http://localhost:9000

dfg:
  rights:
    owner: "Bayerische Staatsbibliothek"
    owner-contact: "mailto:mdz@digitale-sammlungen.de"
    owner-logo: "https://dfg-viewer.de/typo3temp/assets/images/d08200e38c0994139590ea9ad0b5c4fa.jpg"
    owner-site-url: "https://www.bsb-muenchen.de/"

iiif:
  identifier:
    namespaces:
      - 'mdz-obj'
      - 'mdz-obj-child'
  presentation:
    #baseUrl: "http://localhost:23232/presentation/v2/"
    baseUrl: "https://api-dev.digitale-sammlungen.de/iiif/presentation/v2/"

oai:
  identify:
    admin-email: "mdz@digitale-sammlungen.de"
    base-url: "http://localhost:8080/oai/v2"
    repository-identifier: "oai.digitale-sammlungen.de"
    repository-name: "Digitale Sammlungen (MDZ)"
    sample-id: "f611580a-1106-4c74-851f-9a6d12cb662c"
    
    
management:
  endpoints:
    web:
      base-path: "/monitoring"
      exposure:
        include:
          - prometheus
          - metrics
          - info
          - health
  server:
    port: 18081

server:
  port: 8081
  server-header: "@project.name@ v@project.version@"

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: MONITORING